### ISSUE TITLE
Feature Request: Allow extra SSH kwargs when connecting to remote kernel

### ISSUE THREAD

**Issue by jacksund** [spyder-ide/spyder-kernels#359]
When connecting to an existing kernel, can Spyder allow extra ssh options?

For example, I would like to add a jump host (-J) to my ssh. So instead of `ssh user1@hostA`, Spyder would also allow `ssh user1@hostA -J user1@hostB`.

**Comment by jacksund** [comment]
This use-case is probably too niche to be used widely. Closing for lack of interest.

**Comment by ccordoba12** [comment]
Hey @jacksund, sorry for not responding before. The thing is I don't know how to pass those arguments to the ssh tunnel we create to connect to a remote kernel.

That's done in Spyder, not here, specifically on this file:

https://github.com/spyder-ide/spyder/blob/5.x/spyder/plugins/ipythonconsole/widgets/kernelconnect.py

You can try to extend that dialog to add the jump option to it, and then use that info when creating a client for the external kernel. Since this is a bit niche, as you said, we'd have to rely on you for that.

**Comment by jacksund** [comment]
No worries @ccordoba12 ! I learned that this feature wouldn't be allowed on my university cluster anyways. So I'll likely abandon this feature request :cry:

Alternatively, I think more people would be interested in this feature request: https://github.com/spyder-ide/spyder-kernels/issues/358. I rewrote that issue so the request is clearer too.
