### ISSUE TITLE
Suggestion: Drop support for Python versions < 3.7

### ISSUE THREAD

**Issue by aqeelat** [spyder-ide/spyder-kernels#462]
I can try taking on this task.

**Comment by ccordoba12** [comment]
Hey @aqeelat, thanks for the suggestion. The migration to Python 3, plus dropping support for versions older than 3.7, was already done in our `master` branch, which is going to be part of the future Spyder-kernels 3.0.

For Spyder-kernels 2, we decided to keep compatibility with Python 2 because that version is now in maintenance mode and we don't want to make major changes to it,
